version: '2'
services:
  redis-cluster:
    environment:
     IP: ${REDIS_CLUSTER_IP}
    build:
      context: .
      args:
        redis_version: '4.0.10'
    hostname: server
    ports:
      - '7000-7008:7000-7008'
      - '5000-5002:5000-5002'
